version: '3'
services:
  site:
    image: magento/php:7.0
    volumes:
      - ../source:/var/www/html
    ports:
      - 80:80
      - 443:443
  db:
    image: magento/mariadb:10.5.5
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example



